### ISSUE TITLE
Error in Input_POGENOM.sh

### ISSUE THREAD

**Issue by asierzaragoza** [EnvGen/POGENOM#13]
Hi! I am having an issue running your program. I organised the input files as specified in the user guide, but I am running into an error in the first step of the pipeline. Here is my output:

```
INFO: Starting Input_POGENOM pipeline - Working directory: /home/jroda/programs/POGENOM/Input_POGENOM
INFO: Generating Reads subsets - Fraction used 0.15
      Subset ERR3589573_R1.fq.gz already created
      Subset ERR3589573_R2.fq.gz already created
INFO: Calculating Genome Median coverage - sub-samples - Median coverage threshold 20
INFO: Calculating Genome Median coverage and breadth - Dataset: ERR3589573 - Median coverage threshold: 20 - Breadth threshold: 40 %
INFO: Generating VCF files - Genome 3300027839_77
INFO: Generating VCF files - Genome 3300027801_55
INFO: Generating VCF files - Genome 3300032151_26
INFO: Generating VCF files - Genome 3300009425_20
INFO: Generating VCF files - Genome 3300031639_23
INFO: Generating VCF files - Genome 3300027847_65
Error on line 91 - script Input_POGENOM.sh

```

Looking at the script, it seems like it´s looking for an # symbol that it is not present in the file. Do you hve any idea on what can be the issue?

**Comment by lfdelzam** [comment]
Could you please share the Selected_samples_Genomes.txt file and the log_files/ERR3589573.3300027847_65_vcf_files.log.
Thanks

**Comment by asierzaragoza** [comment]
My log_files folder is empty, but here is the Selected_samples_Genomes.txt file:

[Selected_samples_Genomes.txt](https://github.com/EnvGen/POGENOM/files/8908731/Selected_samples_Genomes.txt)

**Comment by lfdelzam** [comment]
A new version of Input Pogenom pipeline is now available. You can use now Bowtie2 or Bwa-MEM2 + CoverM. The default aligner is bowtie2 with parameters as in the paper.
