### ISSUE TITLE
Input Data Setup

### ISSUE THREAD

**Issue by cliffbueno** [EnvGen/POGENOM#17]
Hello,
I checked the documentation but am still confused about how to organize the input files.

I get that I should put metagenomic reads (say forward and reverse from 2 samples) Metagenome_A_R1.fq.gz and Metagenome_A_R2.fq.gz in directory Metagenome_A and Metagenome_B_R1.fq.gz and Metagenome_B_R2.fq.gz in directory Metagenome_B, all in the RAW_DATA/Reads directory.

What I'm confused on is the genome part. It says "Create a directory for each dataset:". Is "dataset" the correct terminology here or should it be "Create a directory for each genome:"? Say I want to map reads from both of those samples to 2 reference genomes (which are not bins from either of those samples). In the RAW_DATA/Genomes directory do I need a directory called Taxa1 with Taxa1.fa and another directory called Taxa2 with Taxa2.fa inside? Or, do I need to make a directory Metagenome_A with Taxa1.fa and Taxa2.fa and then directory Metagenome_B with Taxa1.fa and Taxa2.fa inside?

Thank you,

Cliff

**Comment by lfdelzam** [comment]
Paired-Reads (Fwd and Revs) in Reads/datasetN/*
Will be mapped against each genome in Genomes/datasetN/*

Reads/datasetN/* contains paired-reads from one or several samples

And Genomes/datasetN/* contains one or several genomes (or MAGs)

**Comment by cliffbueno** [comment]
Ok, thanks for clarifying. So if I want the reads from different metagenomes mapped to the same set of genomes, I need to copy those genomes over and over again into different directories with each of the metagenome names.

**Comment by lfdelzam** [comment]
No, put the genomes in one directory.

**Comment by cliffbueno** [comment]
Oh okay, thanks for clarifying - that makes more sense! I was confused about the meaning of "dataset" versus "sample".
