### ISSUE TITLE
Error on line 119 - script Input_POGENOM.sh

### ISSUE THREAD

**Issue by cliffbueno** [EnvGen/POGENOM#18]
Hello,
I got all the files input correctly and the filtering step in Input_POGENOM worked.
It looks like Input_POGENOM proceeded to the "Generating VCF files" point. I see that the 02_MAPPING and 03_MPILEUP directories were created in the PREFILT directory. But then there was this error:
"Error on line 119 - script Input_POGENOM.sh"

I also noticed in the log_files there is an AttributeError in line 22:
'int' object has no attribute 'split'

Please let me know if you know how to troubleshoot those or if you need more log information. Thanks!

**Comment by lfdelzam** [comment]
Please share the log files. Thanks

**Comment by cliffbueno** [comment]
[Aus.Mycobacterium_vcf_files.log](https://github.com/user-attachments/files/16655308/Aus.Mycobacterium_vcf_files.log)
[Aus.Mycobacterium.coverage_breadth.log](https://github.com/user-attachments/files/16655309/Aus.Mycobacterium.coverage_breadth.log)
There were some other genomes too, but those logs are the same.
[samples_filter_Aus.log](https://github.com/user-attachments/files/16655310/samples_filter_Aus.log)

**Comment by lfdelzam** [comment]
Please double-check that the Reads and Genomes files follow the required name structure.

**Comment by cliffbueno** [comment]
I'm pretty sure.
RAW_DATA/Reads/Aus:
-rw-r--r--. 1 clbd1748 1.7G Aug 15 10:57 12830_2_R1.fastq.gz
-rw-r--r--. 1 clbd1748 1.8G Aug 15 11:00 12830_2_R2.fastq.gz
-rw-r--r--. 1 clbd1748 628M Aug 15 11:09 19517_1_R1.fastq.gz
-rw-r--r--. 1 clbd1748 731M Aug 15 11:11 19517_1_R2.fastq.gz
-rw-r--r--. 1 clbd1748 1.3G Aug 15 11:19 12485_1_R1.fastq.gz
-rw-r--r--. 1 clbd1748 1.5G Aug 15 11:20 12485_1_R2.fastq.gz

RAW_DATA/Genomes/Aus:
-rw-------. 1 clbd1748 9.2M Aug 14 23:23 Haliangium.fa
-rw-------. 1 clbd1748 2.4M Aug 14 23:31 Acidothermus.fa
-rw-------. 1 clbd1748 5.6M Aug 14 23:36 Bryobacter.fa
-rw-------. 1 clbd1748 7.3M Aug 14 23:45 Solibacter.fa
-rw-------. 1 clbd1748 4.3M Aug 14 23:48 Mycobacterium.fa
-rw-------. 1 clbd1748 4.1M Aug 14 23:49 Bacillus.fa
-rw-------. 1 clbd1748 8.9M Aug 14 23:51 Bradyrhizobium.fa
-rw-------. 1 clbd1748 2.7M Aug 14 23:55 Udaeobacter.fa

In the config file:
  "genomes_ext": ".fa",
  "reads_ext": ".fastq.gz",

**Comment by lfdelzam** [comment]
Did you provide the Reads' fwd and rev_index (ex, _R1, _R2) in the config file?

**Comment by cliffbueno** [comment]
Yes I have just checked and it is there
  "fwd_index": "_R1",
  "rev_index": "_R2",

**Comment by lfdelzam** [comment]
you are using a python version 3.10.2 while Input Pogenom conda envirement uses the version python=3.7.8.
Did you install the ip_env?

conda env create -f config_files/Input_POGENOM_conda_env_setup.yaml

**Comment by cliffbueno** [comment]
Yes I did do that, but my HPC IT support has informed that there were some deeper issues in some of my conda environments which have now been fixed, so I will try again.

**Comment by cliffbueno** [comment]
I'm still getting the error on line 119 error. When I activate the ip_env, the Python version is correct.

(base) [clbd1748@login12 Input_POGENOM]$ conda activate ip_env
(ip_env) [clbd1748@login12 Input_POGENOM]$ python --version
Python 3.7.8

**Comment by lfdelzam** [comment]
Please send me the file   Selected_samples_Genomes.txt

**Comment by lfdelzam** [comment]
And the log files with the new python version

**Comment by cliffbueno** [comment]
Okay, here's that, and the Myco logs again (there are also logs for the other taxa, they look the same, except the line 22 error is 'int' object has no attribute 'split' instead of 'tuple' object has no attribute 'split').
[Selected_samples_Genomes.txt](https://github.com/user-attachments/files/16738505/Selected_samples_Genomes.txt)
[samples_filter_Aus.log](https://github.com/user-attachments/files/16738506/samples_filter_Aus.log)
[Aus.Mycobacterium_vcf_files.log](https://github.com/user-attachments/files/16738507/Aus.Mycobacterium_vcf_files.log)
[Aus.Mycobacterium.coverage_breadth.log](https://github.com/user-attachments/files/16738508/Aus.Mycobacterium.coverage_breadth.log)

**Comment by lfdelzam** [comment]
In the samples_filter.log, your Python version is still 3.10: 
/curc/sw/install/python/3.10.2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3464


Since you have a few genomes and reads, maybe you could run input pogenom without the prefilt option. In this way, you will skip the step where the split() function is used.

**Comment by cliffbueno** [comment]
Interesting. I will see if I can troubleshoot the python issue on my end. I am not using Snakemake outside the ip_env.

Also yes I am testing on 3 samples but eventually want to run on 50!

**Comment by lfdelzam** [comment]
Since your sample names are composed of numbers, the read line from the selected samples file is not  read as a string by Python 3.10. I would need to add str() function to some snakemake files. An easier way around would be to start your sample name by a letter.

**Comment by cliffbueno** [comment]
Okay, I will rename my samples to start with a letter!

**Comment by cliffbueno** [comment]
It worked! Thank you very much for the help. I would just suggest adding a line in the documentation "Sample names should start with a letter".

**Comment by lfdelzam** [comment]
Since your sample names are composed of numbers, the read line from the selected samples file is not  read as a string by  Python 3.10 from the environment you are using. I would need to add str() function to some snakemake files. An easier way around would be to start your sample name by a letter. 

I think this is a conda environment issue.
