### ISSUE TITLE
exited with non-zero exit code

### ISSUE THREAD

**Issue by Thexiyang** [EnvGen/POGENOM#4]
Thanks for the nice tool! When I run this tool on my data, I came across this error: exited with non-zero exit code. This occurred at this step: bowtie2 + samtools view. Could you provide some guidance here?

**Comment by lfdelzam** [comment]
Hi, Thanks. The pipeline output some tips when an error occurs. Have you followed those tips? Otherwise, Could you please share the log files? Particularly, the 02_MAPPING/log_bowtie2/<dataset>/<genome_name>/<sample_name>_<genome_name>_mpq_<min mapping quality>.log file.
