### ISSUE TITLE
add bwa-mem2 support to improve mapping speed

### ISSUE THREAD

**Issue by jianshu93** [EnvGen/POGENOM#5]
Dear author, 

It would be nice to add bwa-mem2 support for linux (conda install -c bioconda bwa-mem2) for large dataset like a few hundred samples. Bowtie2 does not scale well with increasing threads (core dumped for large threads). Should be very easy, just the index and mapping step. All others are the same:

bwa-mem2 index ${output}/all_mags_rename.fasta
bwa-mem2 mem -t $threads -p ${output}/all_mags_rename.fasta $reads1 $reads2 > ${output}/all_mags_rename.sam

Thanks,

Jianshu

**Comment by jianshu93** [comment]
bam filtering can be then done using coverm filter acording to alignment ratio and identity.

**Comment by lfdelzam** [comment]
the new version 0.8.4 includes BWA-MEM2 + CoverM
