### ISSUE TITLE
large dataset fail but small one works

### ISSUE THREAD

**Issue by jianshu93** [EnvGen/POGENOM#8]
Hello POGENOM team,

See error for a bunch for samples in a dataset (small samples are ok):

INFO: Starting Input_POGENOM pipeline - Working directory: /storage/home/hcoda1/4/jzhao399/p-ktk3-0/rich_project_bio-konstantinidis/POGENOM/Input_POGENOM
INFO: Generating Reads subsets - Fraction used 0.15
      Subset LL_1001_R1.fq.gz created - Number of reads in subset: 3663575
      Subset LL_1001_R2.fq.gz created - Number of reads in subset: 3663575
      Subset LL_1002_R1.fq.gz created - Number of reads in subset: 1923832
      Subset LL_1002_R2.fq.gz created - Number of reads in subset: 1923832
      Subset LL_1003_R1.fq.gz created - Number of reads in subset: 1617946
      Subset LL_1003_R2.fq.gz created - Number of reads in subset: 1617946
      Subset LL_1004_R1.fq.gz created - Number of reads in subset: 2837179
      Subset LL_1004_R2.fq.gz created - Number of reads in subset: 2837179
      Subset LL_1005_R1.fq.gz created - Number of reads in subset: 2718667
      Subset LL_1005_R2.fq.gz created - Number of reads in subset: 2718667
      Subset LL_1006_R1.fq.gz created - Number of reads in subset: 2523722
      Subset LL_1006_R2.fq.gz created - Number of reads in subset: 2523722
      Subset LL_1007_R1.fq.gz created - Number of reads in subset: 2038669
      Subset LL_1007_R2.fq.gz created - Number of reads in subset: 2038669
      Subset LL_1008_R1.fq.gz created - Number of reads in subset: 2627007
      Subset LL_1008_R2.fq.gz created - Number of reads in subset: 2627007
      Subset LL_1009_R1.fq.gz created - Number of reads in subset: 1028798
      Subset LL_1009_R2.fq.gz created - Number of reads in subset: 1028798
      Subset LL_1010_R1.fq.gz created - Number of reads in subset: 2621093
      Subset LL_1010_R2.fq.gz created - Number of reads in subset: 2621093
      Subset LL_1011_R1.fq.gz created - Number of reads in subset: 1360653
      Subset LL_1011_R2.fq.gz created - Number of reads in subset: 1360653
      Subset LL_1012_R1.fq.gz created - Number of reads in subset: 1390948
      Subset LL_1012_R2.fq.gz created - Number of reads in subset: 1390948
      Subset LL_1013_R1.fq.gz created - Number of reads in subset: 1726329
      Subset LL_1013_R2.fq.gz created - Number of reads in subset: 1726329
      Subset LL_1014_R1.fq.gz created - Number of reads in subset: 926951
      Subset LL_1014_R2.fq.gz created - Number of reads in subset: 926951
      Subset LL_1015_R1.fq.gz created - Number of reads in subset: 2990884
      Subset LL_1015_R2.fq.gz created - Number of reads in subset: 2990884
      Subset LL_1016_R1.fq.gz created - Number of reads in subset: 2804597
      Subset LL_1016_R2.fq.gz created - Number of reads in subset: 2804597
      Subset LL_1017_R1.fq.gz created - Number of reads in subset: 2831833
      Subset LL_1017_R2.fq.gz created - Number of reads in subset: 2831833
      Subset LL_1018_R1.fq.gz created - Number of reads in subset: 2732407
      Subset LL_1018_R2.fq.gz created - Number of reads in subset: 2732407
      Subset LL_1019_R1.fq.gz created - Number of reads in subset: 1845187
      Subset LL_1019_R2.fq.gz created - Number of reads in subset: 1845187
      Subset LL_1020_R1.fq.gz created - Number of reads in subset: 2732976
      Subset LL_1020_R2.fq.gz created - Number of reads in subset: 2732976
      Subset LL_1021_R1.fq.gz created - Number of reads in subset: 1776962
      Subset LL_1021_R2.fq.gz created - Number of reads in subset: 1776962
      Subset LL_1022_R1.fq.gz created - Number of reads in subset: 1085073
      Subset LL_1022_R2.fq.gz created - Number of reads in subset: 1085073
      Subset LL_1023_R1.fq.gz created - Number of reads in subset: 2566383
      Subset LL_1023_R2.fq.gz created - Number of reads in subset: 2566383
      Subset LL_1024_R1.fq.gz created - Number of reads in subset: 2824773
      Subset LL_1024_R2.fq.gz created - Number of reads in subset: 2824773
      Subset LL_1025_R1.fq.gz created - Number of reads in subset: 1632972
      Subset LL_1025_R2.fq.gz created - Number of reads in subset: 1632972
      Subset LL_1026_R1.fq.gz created - Number of reads in subset: 1517751
      Subset LL_1026_R2.fq.gz created - Number of reads in subset: 1517751
      Subset LL_1027_R1.fq.gz created - Number of reads in subset: 2169901
      Subset LL_1027_R2.fq.gz created - Number of reads in subset: 2169901
      Subset LL_1028_R1.fq.gz created - Number of reads in subset: 2471029
      Subset LL_1028_R2.fq.gz created - Number of reads in subset: 2471029
      Subset LL_1029_R1.fq.gz created - Number of reads in subset: 1532065
      Subset LL_1029_R2.fq.gz created - Number of reads in subset: 1532065
      Subset LL_1030_R1.fq.gz created - Number of reads in subset: 1328189
      Subset LL_1030_R2.fq.gz created - Number of reads in subset: 1328189
      Subset LL_1031_R1.fq.gz created - Number of reads in subset: 1798547
      Subset LL_1031_R2.fq.gz created - Number of reads in subset: 1798547
      Subset LL_1032_R1.fq.gz created - Number of reads in subset: 2613616
      Subset LL_1032_R2.fq.gz created - Number of reads in subset: 2613616
      Subset LL_1033_R1.fq.gz created - Number of reads in subset: 2986771
      Subset LL_1033_R2.fq.gz created - Number of reads in subset: 2986771
      Subset LL_1034_R1.fq.gz created - Number of reads in subset: 2952963
      Subset LL_1034_R2.fq.gz created - Number of reads in subset: 2952963
      Subset LL_1035_R1.fq.gz created - Number of reads in subset: 1365034
      Subset LL_1035_R2.fq.gz created - Number of reads in subset: 1365034
      Subset LL_1036_R1.fq.gz created - Number of reads in subset: 1559094
      Subset LL_1036_R2.fq.gz created - Number of reads in subset: 1559094
INFO: Calculating Genome Median coverage - sub-samples - Median coverage threshold 20
./Input_POGENOM.sh: line 119: 84628 Killed                  snakemake -s snakefiles/step_filter -j $threads $extra_params 2> log_files/samples_filter_$dataset.log
Error on line 78 - script Input_POGENOM.sh
ls: write error: Broken pipe
TIP 1 - Look at /storage/home/hcoda1/4/jzhao399/p-ktk3-0/rich_project_bio-konstantinidis/POGENOM/Input_POGENOM/log_files/samples_filter_Lanier.log
TIP 2 - Check if the 'ip_env' has been activated - command:
    'conda activate ip_env'
TIP 3 - Use the command:
    'snakemake -s snakefiles/step_filter --unlock'
     and run the pipeline again
21843.95user 531.02system 6:20:27elapsed 98%CPU (0avgtext+0avgdata 209711760maxresident)k

Any idea?

Thanks,

It seems the ls command error.

Jianshu

**Comment by 473021677** [comment]
Hi,
   I  have encountered the same problem. I am using the POGENOM software to calculate the population genetic parameters. When I use the Input_POGENOM pipeline to generate the VCF file by mapping one metagenome sample aginst one reference genome, everything is OK. But When I map two metagenome samples aginst one reference genome, the program terminated abnormally.  have appended the log files and the json file.
[Input_POGENOM_config.json.txt](https://github.com/EnvGen/POGENOM/files/7909683/Input_POGENOM_config.json.txt)
[nohup.out.txt](https://github.com/EnvGen/POGENOM/files/7909684/nohup.out.txt)
[samples_filter_PRE_project.log](https://github.com/EnvGen/POGENOM/files/7909685/samples_filter_PRE_project.log)

**Comment by lfdelzam** [comment]
We highly recommend installing the pipeline using conda env create -f config_files/Input_POGENOM_conda_env_setup.yaml.
Make sure you have enough CPUs and ram memory to run the pipeline. We recommend using at least 20 CPUs for large datasets.

**Comment by jianshu93** [comment]
Hi YangYuan，

It seems the last suggestion:

TIP 3 - Use the command:
    'snakemake -s snakefiles/step_filter --unlock'
     and run the pipeline again


works for me.

But the biggest problem is memory for larger number of metagenomes and genomes. For more questions My WeChat is JansueChao and email jianshu.zhao@gatech.edu

Thanks

**Comment by jianshu93** [comment]
Hello,

Last time I suggest we change to bwa-mem2/mem for large reference genomes. You mentioned that @lfdelzam bowtie2 parameters can be used to filtering high identity matches. However, even with sorted bam file we can still filter by identity and reads alignment ratio, which is implemented in CoverM filter command, it is extremely fast and accurate. I want to know whether you agree with it so that I can have an PR and then you could merge it.  This is very important for large dataset, when bowtie always fails. For accuracy of different mapper, I did a comparison here: https://github.com/jianshu93/Competitive_mapping

By the way bowtie2 is extremely bad for short contigs. See a system comparison here:
[Gene_Coverage_Calculaton.pdf](https://github.com/EnvGen/POGENOM/files/8646323/Gene_Coverage_Calculaton.pdf)

Thanks,

Jianshu

**Comment by lfdelzam** [comment]
Please fork it and then, once it is ready I can test it and merge it.
Best,
________________________________
