### ISSUE TITLE
Multiple samples failed

### ISSUE THREAD

**Issue by 473021677** [EnvGen/POGENOM#9]
Hi,
I am using the POGENOM software to calculate the population genetic parameters. When I use the Input_POGENOM pipeline to generate the VCF file by mapping one metagenome sample aginst one reference genome, everything is OK. But When I map two metagenome samples aginst one reference genome, the program terminated abnormally. I have appended the log files and the json file. I need your help. If you could help, I really appreciate. Thanks.
[Input_POGENOM_config.json.txt](https://github.com/EnvGen/POGENOM/files/7909700/Input_POGENOM_config.json.txt)
[nohup.out.txt](https://github.com/EnvGen/POGENOM/files/7909701/nohup.out.txt)
[samples_filter_PRE_project.log](https://github.com/EnvGen/POGENOM/files/7909702/samples_filter_PRE_project.log)

Best regards,
YangYuan

**Comment by lfdelzam** [comment]
The Snakemake version recommended is 5.5.0. We highly recommend installing the pipeline using conda env create -f config_files/Input_POGENOM_conda_env_setup.yaml
